# Generated by Django 4.2.7 on 2025-05-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0003_alter_business_name'),
        ('item_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_management.business'),
            preserve_default=False,
        ),
    ]
