# Generated by Django 4.2.7 on 2025-05-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authuser',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('WORKER', 'Worker'), ('SUPERADMIN', 'Superadmin')], default='CLIENT', max_length=10),
        ),
    ]
