# Generated by Django 4.2.7 on 2025-05-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0001_initial'),
        ('category_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='business_management.business'),
            preserve_default=False,
        ),
    ]
