# Generated by Django 4.2.7 on 2025-05-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
